import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import { cookies } from "next/headers";

import "./globals.css";
import AppSidebar from "@/src/components/AppSidebar";
import Navbar from "@/src/components/Navbar";
import { ThemeProvider } from "@/src/providers/theme-provider";
import { SidebarProvider } from "@/src/components/ui/sidebar";

const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "charts2u",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "open";

  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={`${raleway.className} antialiased flex`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />

            <main className="w-full">
              <Navbar />
              <div className="px-4">{children}</div>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
