import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppSidebar from "@/src/components/AppSidebar";
import Navbar from "@/src/components/Navbar";
import { ThemeProvider } from "@/src/providers/theme-provider";
import { SidebarProvider } from "@/src/components/ui/sidebar";
import { cookies } from "next/headers";

// Configuração da fonte Inter do Google Fonts
// subset: latin para caracteres latinos, display: swap para melhor performance
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

// Metadados da aplicação que aparecem no título e descrição da página
export const metadata: Metadata = {
  title: "charts2u",
  description: "Generated by create next app",
};

// Layout raiz da aplicação (Server Component assíncrono)
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Acessa os cookies do servidor para verificar o estado da sidebar
  const cookieStore = await cookies();
  // Verifica se a sidebar deve iniciar aberta ou fechada baseado no cookie salvo
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "open";

  return (
    // suppressHydrationWarning evita avisos de hidratação devido ao tema
    <html lang="pt-br" suppressHydrationWarning>
      {/* Aplica a fonte Inter e antialiased para melhor renderização do texto */}
      <body className={`${inter.className} antialiased flex`}>
        {/* Provider de tema para modo claro/escuro */}
        {/* attribute="class" adiciona classe dark/light ao HTML */}
        {/* defaultTheme="system" usa a preferência do sistema operacional */}
        {/* enableSystem permite detecção automática do tema do sistema */}
        {/* disableTransitionOnChange evita animações ao trocar tema */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Provider da sidebar com estado inicial baseado no cookie */}
          <SidebarProvider defaultOpen={defaultOpen}>
            {/* Sidebar lateral da aplicação */}
            <AppSidebar />

            {/* Área principal do conteúdo */}
            <main className="w-full">
              {/* Barra de navegação superior */}
              <Navbar />
              {/* Container do conteúdo das páginas com padding horizontal */}
              <div className="px-4">{children}</div>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
